version: '3'

services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: always
    networks:
      - web
    ports:
      - "80:80"
    volumes:
      - "/Users/lusecond/data/www:/Users/lusecond/data/www" #www 代码目录
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf" #nginx 配置
      - "./nginx/servers:/etc/nginx/servers" #nginx 主机配置

  php:
    build:
      context: ./php-fpm
    container_name: php
    restart: always
    networks:
      - web
    volumes:
      #- "./data/www:/data/www"
      - "/Users/lusecond/data/www:/Users/lusecond/data/www" #www 代码目录
      - "./php-fpm/ext-conf.ini:/usr/local/etc/php/conf.d/ext-conf.ini" #php 扩展配置
    

networks:
  web:

